name: Build ffmpeg-kit full LTS (Android)

on:
  workflow_dispatch:
    inputs:
      enable_gpl:
        description: 'Enable GPL codecs (x264/x265, etc.)'
        required: false
        default: 'false'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      # 0) Use Java 17 BEFORE touching the Android SDK
      - name: Set up Java 17 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Check Java
        run: |
          java -version
          echo "JAVA_HOME=$JAVA_HOME"

      # 1) Install Android SDK / cmdline-tools and accept licenses
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          accept-android-sdk-licenses: true

      # 2) Install platform + NDK r23c (LTS-friendly)
      - name: Install NDK r23c and platforms
        run: |
          sdkmanager --install "platform-tools" "platforms;android-29" "ndk;23.2.8568313"
          echo "ANDROID_SDK_ROOT=${ANDROID_SDK_ROOT}" >> $GITHUB_ENV
          echo "ANDROID_NDK_ROOT=${ANDROID_SDK_ROOT}/ndk/23.2.8568313" >> $GITHUB_ENV

      # 3) Fetch ffmpeg-kit
      - name: Checkout ffmpeg-kit
        uses: actions/checkout@v4
        with:
          repository: arthenica/ffmpeg-kit
          fetch-depth: 0

      # 4) Build (Full + LTS; toggle GPL via input)
      - name: Build (Full + LTS)
        run: |
          set -e
          chmod +x android.sh
          if [ "${{ github.event.inputs.enable_gpl }}" = "true" ]; then
            ./android.sh --full --enable-gpl --lts
          else
            ./android.sh --full --lts
          fi

      # 5) Publish artifacts
      - name: Upload AARs
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-kit-android-full-LTS
          path: prebuilt/bundle-android-aar-lts/*.aar

      - name: Upload build log
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: build.log
