name: Build FFmpegKit AAR

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-android-aar:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Android NDK
      uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r25b # Or your desired NDK version

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y autoconf automake libtool pkg-config curl cmake gperf texinfo yasm nasm bison autogen git wget autopoint meson ninja

    - name: Set Android environment variables
      run: |
        echo "ANDROID_SDK_ROOT=${{ steps.setup-ndk.outputs.android-sdk-root }}" >> $GITHUB_ENV
        echo "ANDROID_NDK_ROOT=${{ steps.setup-ndk.outputs.ndk-path }}" >> $GITHUB_ENV

    - name: Build FFmpegKit AAR
      run: |
        # Clone FFmpegKit if not already part of your repo, or navigate to its directory
        # git clone https://github.com/arthenica/ffmpeg-kit.git
        # cd ffmpeg-kit
        ./android.sh # Add options like --enable-gpl, --enable-fontconfig as needed

    - name: Upload AAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: ffmpeg-kit-aar
        path: prebuilt/*.aar
