name: Build FFmpegKit AAR

on:
  push:
    paths:
      - 'app/**/*.gradle'
      - 'cpp/**'
      - '.github/workflows/build-aar.yml'

jobs:
  build-aar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Set up Android SDK & NDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 29
          ndk-version: '25.2.9519653'
          cmake-version: '3.22.1'
          components: tools, platform-tools

      - name: Build FFmpegKit full AAR
        run: |
          chmod +x android.sh
          ./android.sh --lts --full

      - name: Upload AAR Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ffmpeg-kit-full-aar
          path: prebuilt/bundle-android-aar-lts/*.aar
